# Generated by Django 5.1.1 on 2024-11-26 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('comfort_class_car_transfer_price', models.PositiveIntegerField()),
                ('business_class_car_transfer_price', models.PositiveIntegerField()),
                ('van_transfer_price', models.PositiveIntegerField()),
                ('windshield_washer_price_per_bottle', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'car wash',
                'verbose_name_plural': 'car washes',
            },
        ),
        migrations.CreateModel(
            name='CarWashService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_countable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='car_washes.carwashservice')),
            ],
            options={
                'verbose_name': 'car wash service',
                'verbose_name_plural': 'car wash services',
            },
        ),
        migrations.CreateModel(
            name='CarWashServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='car_washes.carwash')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='car_washes.carwashservice')),
            ],
            options={
                'verbose_name': 'car wash service price',
                'verbose_name_plural': 'car wash service prices',
            },
        ),
    ]
