# Generated by Django 5.1.1 on 2024-11-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwash',
            options={'verbose_name': 'car wash', 'verbose_name_plural': 'car washes'},
        ),
    ]
