# Generated by Django 5.1.1 on 2024-11-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashServicePrice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_washes.carwash')),
            ],
            options={
                'verbose_name': 'car wash service price',
                'verbose_name_plural': 'car wash service prices',
            },
        ),
    ]
