# Generated by Django 5.1.1 on 2024-11-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carwash',
            old_name='business_class_car_transfer_price',
            new_name='business_class_car_washing_price',
        ),
        migrations.RenameField(
            model_name='carwash',
            old_name='comfort_class_car_transfer_price',
            new_name='comfort_class_car_washing_price',
        ),
        migrations.RenameField(
            model_name='carwash',
            old_name='van_transfer_price',
            new_name='van_washing_price',
        ),
    ]
