# Generated by Django 5.1.1 on 2024-11-05 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0002_carwashserviceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_washes.carwash')),
            ],
            options={
                'verbose_name': 'car wash service price',
                'verbose_name_plural': 'car wash service prices',
            },
        ),
        migrations.DeleteModel(
            name='CarWashServicePrice',
        ),
    ]
