# Generated by Django 5.1.1 on 2024-11-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0002_rename_business_class_car_transfer_price_carwash_business_class_car_washing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashservice',
            name='is_dry_cleaning',
            field=models.BooleanField(default=False),
        ),
    ]
