# Generated by Django 5.1.7 on 2025-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0003_alter_carwashserviceprice_car_wash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashservice',
            name='max_count',
            field=models.PositiveIntegerField(default=1000000, verbose_name='Max count'),
        ),
    ]
