# Generated by Django 5.1.1 on 2024-11-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0003_carwashservice_delete_carwashserviceprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwashservice',
            options={'verbose_name': 'car wash service', 'verbose_name_plural': 'car wash services'},
        ),
    ]
