# Generated by Django 5.1.7 on 2025-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0004_carwashservice_max_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='car_transporters_and_washers_business_class_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Car transporters and washers business class price'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='car_transporters_and_washers_comfort_class_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Car transporters and washers comfort class price'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='car_transporters_and_washers_van_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Car transporters and washers van price'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='car_transporters_and_washers_windshield_washer_price_per_bottle',
            field=models.PositiveIntegerField(default=0, verbose_name='Car transporters and washers windshield washer price per bottle'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='business_class_car_washing_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Car transporter business class price'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='comfort_class_car_washing_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Car transporter comform class price'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Car wash name'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='van_washing_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Car transporter van price'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='windshield_washer_price_per_bottle',
            field=models.PositiveIntegerField(default=0, verbose_name='Windshield washer price per bottle'),
        ),
    ]
