# Generated by Django 5.1.1 on 2024-11-18 04:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0004_alter_carwashservice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashservice',
            name='car_wash',
        ),
        migrations.RemoveField(
            model_name='carwashservice',
            name='price',
        ),
        migrations.AlterField(
            model_name='carwashservice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CarWashServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='car_washes.carwash')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='car_washes.carwashservice')),
            ],
            options={
                'verbose_name': 'car wash service price',
                'verbose_name_plural': 'car wash service prices',
            },
        ),
    ]
