# Generated by Django 5.1.1 on 2024-11-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0005_remove_carwashservice_car_wash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashservice',
            name='is_countable',
            field=models.BooleanField(default=False),
        ),
    ]
