# Generated by Django 5.1.7 on 2025-05-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0005_carwash_car_transporters_and_washers_business_class_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwash',
            name='car_transporters_and_washers_windshield_washer_price_per_bottle',
        ),
    ]
