# Generated by Django 5.1.1 on 2024-11-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0006_carwashservice_is_countable'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashservice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='car_washes.carwashservice'),
        ),
    ]
