# Generated by Django 5.1.7 on 2025-05-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0006_remove_carwash_car_transporters_and_washers_windshield_washer_price_per_bottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashserviceprice',
            name='price_for_car_transporter_and_washer',
            field=models.PositiveIntegerField(default=0, verbose_name='Price per transporter and washer'),
        ),
    ]
