# Generated by Django 5.1.7 on 2025-05-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0007_carwashserviceprice_price_for_car_transporter_and_washer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashserviceprice',
            name='price_for_car_transporter_and_washer',
        ),
    ]
