# Generated by Django 5.1.1 on 2024-11-18 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0007_carwashservice_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashservice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
