# Generated by Django 5.1.1 on 2024-11-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0008_alter_carwashservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwashservice',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
