# Generated by Django 5.1.7 on 2025-05-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0008_remove_carwashserviceprice_price_for_car_transporter_and_washer'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Is hidden'),
        ),
    ]
