# Generated by Django 5.1.7 on 2025-05-17 12:29

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0009_carwash_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Car wash name'),
        ),
        migrations.AddConstraint(
            model_name='carwash',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_car_wash_name'),
        ),
    ]
