# Generated by Django 5.1.5 on 2025-02-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffserviceprice',
            name='service',
            field=models.CharField(choices=[('comfort_class_car_transfer', 'comfort class car transfer'), ('business_class_car_transfer', 'business class car transfer'), ('van_transfer', 'van transfer'), ('car_transporter_extra_shift', 'car transporter extra shift'), ('urgent_wash', 'urgent wash'), ('item_dry_clean', 'item dry clean'), ('under_plan_planned_car_transfer', 'under plan planned car transfer')], max_length=255, unique=True),
        ),
    ]
