# Generated by Django 5.1.1 on 2024-11-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name': 'penalty', 'verbose_name_plural': 'penalties'},
        ),
        migrations.AlterModelOptions(
            name='surcharge',
            options={'verbose_name': 'surcharge', 'verbose_name_plural': 'surcharges'},
        ),
    ]
