# Generated by Django 5.1.1 on 2024-11-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffserviceprice',
            options={'verbose_name': 'staff service price', 'verbose_name_plural': 'staff service prices'},
        ),
    ]
