# Generated by Django 5.1.5 on 2025-02-07 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("economics", "0002_alter_staffserviceprice_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="penalty",
            name="staff",
        ),
        migrations.RemoveField(
            model_name="surcharge",
            name="staff",
        ),
    ]
