# Generated by Django 5.1.1 on 2024-11-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0002_penalty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='consequence',
            field=models.CharField(blank=True, choices=[('dismissal', 'dismissal'), ('warn', 'warn')], max_length=255, null=True),
        ),
    ]
