# Generated by Django 5.1.5 on 2025-02-28 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economics", "0005_penaltyphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="carwashpenalty",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carwashsurcharge",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
    ]
