# Generated by Django 5.1.7 on 2025-03-23 19:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0006_carwashpenalty_date_carwashsurcharge_date'),
        ('staff', '0003_staffregisterrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='shift',
        ),
        migrations.CreateModel(
            name='CarTransporterPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('consequence', models.CharField(blank=True, choices=[('dismissal', 'dismissal'), ('warn', 'warn')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='staff.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'penalty',
                'verbose_name_plural': 'penalties',
            },
        ),
        migrations.AlterField(
            model_name='penaltyphoto',
            name='penalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economics.cartransporterpenalty'),
        ),
        migrations.CreateModel(
            name='CarTransporterSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='staff.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'surcharge',
                'verbose_name_plural': 'surcharges',
            },
        ),
        migrations.DeleteModel(
            name='Surcharge',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
