# Generated by Django 5.1.7 on 2025-04-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0007_remove_penalty_shift_cartransporterpenalty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartransporterpenalty',
            options={'verbose_name': 'Car transporter penalty', 'verbose_name_plural': 'Car transporter penalties'},
        ),
        migrations.AlterModelOptions(
            name='cartransportersurcharge',
            options={'verbose_name': 'Car transporter surcharge', 'verbose_name_plural': 'Car transporter surcharges'},
        ),
    ]
