# Generated by Django 5.1.7 on 2025-05-08 09:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0008_alter_cartransporterpenalty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTransporterAndWasherServicePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_class_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Comfort class car transfer')),
                ('business_class_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Business class car transfer')),
                ('van_transfer', models.PositiveIntegerField(default=0, verbose_name='Van transfer')),
                ('urgent_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Urgent car transfer')),
                ('item_dry_cleaning', models.PositiveIntegerField(default=0, verbose_name='Item dry cleaning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car transporter and washer service price',
                'verbose_name_plural': 'Car transporter and washer service prices',
            },
            bases=(core.models.SingleRowModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CarTransporterServicePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_class_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Comfort class car transfer')),
                ('business_class_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Business class car transfer')),
                ('van_transfer', models.PositiveIntegerField(default=0, verbose_name='Van transfer')),
                ('extra_shift', models.PositiveIntegerField(default=0, verbose_name='Extra shift')),
                ('urgent_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Urgent car transfer')),
                ('item_dry_cleaning', models.PositiveIntegerField(default=0, verbose_name='Item dry cleaning')),
                ('under_plan_planned_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Under plan planned car transfer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car transporter service price',
                'verbose_name_plural': 'Car transporter service prices',
            },
            bases=(core.models.SingleRowModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='StaffServicePrice',
        ),
    ]
