# Generated by Django 5.1.7 on 2025-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0008_alter_cartransporterpenalty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTransporterAndWasherServicePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_class_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Comfort class car transfer')),
                ('business_class_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Business class car transfer')),
                ('van_transfer', models.PositiveIntegerField(default=0, verbose_name='Van transfer')),
                ('urgent_car_transfer', models.PositiveIntegerField(default=0, verbose_name='Urgent car wash')),
                ('item_dry_clean', models.PositiveIntegerField(default=0, verbose_name='Item dry clean')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car transporter and washer service price',
                'verbose_name_plural': 'Car transporter and washer service prices',
            },
        ),
    ]
