# Generated by Django 5.1.7 on 2025-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0008_alter_cartransporterpenalty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTransporterAndWasherServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('comfort_class_car_transfer', 'Comfort class car transfer'), ('business_class_car_transfer', 'Business class car transfer'), ('van_transfer', 'Van transfer'), ('urgent_wash', 'Urgent wash'), ('item_dry_clean', 'Item dry clean')], max_length=255, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car transporter and washer service price',
                'verbose_name_plural': 'Car transporter and washer service prices',
            },
        ),
    ]
