# Generated by Django 5.1.7 on 2025-05-11 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_washes', '0007_carwashserviceprice_price_for_car_transporter_and_washer'),
        ('economics', '0009_cartransporterandwasherserviceprices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartransporterpenalty',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='cartransporterpenalty',
            name='consequence',
            field=models.CharField(blank=True, choices=[('dismissal', 'dismissal'), ('warn', 'warn')], max_length=255, null=True, verbose_name='Consequence'),
        ),
        migrations.AlterField(
            model_name='cartransporterpenalty',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cartransporterpenalty',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='cartransportersurcharge',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='cartransportersurcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cartransportersurcharge',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cartransportersurcharge',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='carwashpenalty',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='carwashpenalty',
            name='car_wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='car_washes.carwash', verbose_name='Car wash'),
        ),
        migrations.AlterField(
            model_name='carwashpenalty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='carwashpenalty',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='carwashpenalty',
            name='reason',
            field=models.TextField(max_length=1024, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='carwashsurcharge',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='carwashsurcharge',
            name='car_wash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='car_washes.carwash', verbose_name='Car wash'),
        ),
        migrations.AlterField(
            model_name='carwashsurcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='carwashsurcharge',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='carwashsurcharge',
            name='reason',
            field=models.TextField(max_length=1024, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='penaltyphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='penaltyphoto',
            name='penalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economics.cartransporterpenalty', verbose_name='Penalty'),
        ),
        migrations.AlterField(
            model_name='penaltyphoto',
            name='photo_url',
            field=models.URLField(verbose_name='Photo URL'),
        ),
    ]
