# Generated by Django 5.1.1 on 2024-10-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('car_sharing_phone_number', models.CharField(max_length=16)),
                ('console_phone_number', models.CharField(max_length=16)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
