# Generated by Django 5.1.1 on 2024-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
