# Generated by Django 5.1.5 on 2025-02-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='car_sharing_phone_number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='staff',
            name='console_phone_number',
            field=models.CharField(max_length=32),
        ),
    ]
