# Generated by Django 5.1.1 on 2024-11-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminstaff',
            options={'verbose_name': 'admin staff', 'verbose_name_plural': 'admin staff list'},
        ),
    ]
