# Generated by Django 5.1.1 on 2024-10-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_last_activity_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shift_schedule_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_schedule_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
