# Generated by Django 5.1.5 on 2025-02-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_car_sharing_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAwaitingStaff',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('car_sharing_phone_number', models.CharField(max_length=32)),
                ('console_phone_number', models.CharField(max_length=32)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'registration awaiting staff',
                'verbose_name_plural': 'registration awaiting staff list',
            },
        ),
    ]
