# Generated by Django 5.1.1 on 2024-11-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_car_sharing_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAvailableDate',
        ),
    ]
