# Generated by Django 5.1.7 on 2025-05-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffregisterrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Car transporter'), (2, 'Car transporter and washer')], default=1),
        ),
        migrations.AddField(
            model_name='staffregisterrequest',
            name='staff_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Car transporter'), (2, 'Car transporter and washer')], default=1),
        ),
    ]
