# Generated by Django 5.1.1 on 2024-10-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_shift_schedule_month_staff_shift_schedule_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='shift_schedule_month',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='shift_schedule_year',
        ),
        migrations.CreateModel(
            name='StaffAvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
