# Generated by Django 5.1.7 on 2025-03-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_staffregisterrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineDepositException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Month')),
                ('report_period_number', models.PositiveSmallIntegerField(choices=[(1, 'First half of month'), (2, 'Second half of month')], verbose_name='Report period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Fine deposit exception',
                'verbose_name_plural': 'Fine deposit exceptions',
                'constraints': [models.UniqueConstraint(fields=('staff', 'year', 'month', 'report_period_number'), name='unique_fine_deposit_exception')],
            },
        ),
    ]
