# Generated by Django 5.1.7 on 2025-05-20 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
        ('staff', '0004_staff_type_staffregisterrequest_staff_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadAccidentDepositException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From date')),
                ('to_date', models.DateField(verbose_name='To date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Road accident deposit exception',
                'verbose_name_plural': 'Road accident deposit exceptions',
                'constraints': [models.CheckConstraint(condition=models.Q(('from_date__lt', models.F('to_date'))), name='from_date_less_than_to_date', violation_error_message='From date must be less than to date.')],
            },
        ),
    ]
