# Generated by Django 5.1.7 on 2025-05-20 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_roadaccidentdepositexception'),
        ('staff', '0004_staff_type_staffregisterrequest_staff_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='finedepositexception',
            name='unique_fine_deposit_exception',
        ),
        migrations.RemoveConstraint(
            model_name='roadaccidentdepositexception',
            name='from_date_less_than_to_date',
        ),
        migrations.RemoveField(
            model_name='finedepositexception',
            name='month',
        ),
        migrations.RemoveField(
            model_name='finedepositexception',
            name='report_period_number',
        ),
        migrations.RemoveField(
            model_name='finedepositexception',
            name='year',
        ),
        migrations.AddField(
            model_name='finedepositexception',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='From date'),
        ),
        migrations.AddField(
            model_name='finedepositexception',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='To date'),
        ),
        migrations.AlterField(
            model_name='finedepositexception',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AddConstraint(
            model_name='finedepositexception',
            constraint=models.CheckConstraint(condition=models.Q(('from_date__lte', models.F('to_date'))), name='fine_deposit_exception_from_date_less_than_to_date', violation_error_message='From date must be less than to date.'),
        ),
        migrations.AddConstraint(
            model_name='roadaccidentdepositexception',
            constraint=models.CheckConstraint(condition=models.Q(('from_date__lte', models.F('to_date'))), name='road_accident_deposit_exception_from_date_less_than_to_date', violation_error_message='From date must be less than to date.'),
        ),
    ]
