# Generated by Django 5.1.1 on 2024-11-24 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_washes', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Month must be at least 1'), django.core.validators.MaxValueValidator(limit_value=12, message='Month cannot be greater than 12')])),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'available date',
                'verbose_name_plural': 'available dates',
                'ordering': ('year', 'month'),
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('statement_photo_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_app_photo_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_extra', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_wash', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_washes.carwash')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
                'unique_together': {('staff', 'date', 'is_extra')},
            },
        ),
        migrations.CreateModel(
            name='CarToWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('car_class', models.CharField(choices=[('comfort', 'Comfort'), ('business', 'Business'), ('van', 'Van')], max_length=16)),
                ('wash_type', models.CharField(choices=[('planned', 'Planned'), ('urgent', 'Urgent')], max_length=16)),
                ('windshield_washer_refilled_bottle_percentage', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_wash', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_washes.carwash')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shift')),
            ],
            options={
                'verbose_name': 'car to wash',
                'verbose_name_plural': 'cars to wash',
                'unique_together': {('number', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='CarToWashAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.cartowash')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_washes.carwashservice')),
            ],
            options={
                'verbose_name': 'additional service',
                'verbose_name_plural': 'additional services',
                'unique_together': {('car', 'service')},
            },
        ),
    ]
