# Generated by Django 5.1.1 on 2024-12-10 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shifts", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("staff", "date", "is_extra")},
        ),
    ]
