# Generated by Django 5.1.1 on 2024-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='service_app_photo_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='statement_photo_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
