# Generated by Django 5.1.1 on 2024-11-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartowashadditionalservice',
            unique_together={('car', 'name')},
        ),
    ]
