# Generated by Django 5.1.1 on 2024-11-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_alter_cartowash_created_at_alter_shift_created_at'),
        ('staff', '0002_alter_adminstaff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartowash',
            name='business_class_car_washing_price',
            field=models.PositiveIntegerField(help_text='price of business class car washing at the moment'),
        ),
        migrations.AlterField(
            model_name='cartowash',
            name='car_class',
            field=models.CharField(choices=[('comfort', 'comfort'), ('business', 'business'), ('van', 'van')], max_length=16),
        ),
        migrations.AlterField(
            model_name='cartowash',
            name='comfort_class_car_washing_price',
            field=models.PositiveIntegerField(help_text='price of comfort class car washing at the moment'),
        ),
        migrations.AlterField(
            model_name='cartowash',
            name='transfer_price',
            field=models.PositiveIntegerField(help_text='price of car transfer at the moment'),
        ),
        migrations.AlterField(
            model_name='cartowash',
            name='van_washing_price',
            field=models.PositiveIntegerField(help_text='price of van washing at the moment'),
        ),
        migrations.AlterField(
            model_name='cartowash',
            name='wash_type',
            field=models.CharField(choices=[('planned', 'planned'), ('urgent', 'urgent')], max_length=16),
        ),
        migrations.AlterField(
            model_name='cartowash',
            name='windshield_washer_price_per_bottle',
            field=models.PositiveIntegerField(help_text='price of windshield washer per bottle at the moment'),
        ),
        migrations.AlterField(
            model_name='cartowashadditionalservice',
            name='price',
            field=models.PositiveIntegerField(help_text='price of additional service at the moment'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('staff', 'date')},
        ),
    ]
