# Generated by Django 5.1.1 on 2024-11-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_shift_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartowash',
            options={'verbose_name': 'car to wash', 'verbose_name_plural': 'cars to wash'},
        ),
        migrations.AlterModelOptions(
            name='cartowashadditionalservice',
            options={'verbose_name': 'additional service', 'verbose_name_plural': 'additional services'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'shift', 'verbose_name_plural': 'shifts'},
        ),
        migrations.AlterUniqueTogether(
            name='cartowash',
            unique_together={('number', 'shift')},
        ),
    ]
