# Generated by Django 5.1.1 on 2024-11-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_availabledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='confirmed_at',
        ),
    ]
