# Generated by Django 5.1.1 on 2024-11-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_alter_cartowash_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_active',
        ),
        migrations.AddField(
            model_name='shift',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
