# Generated by Django 5.1.4 on 2024-12-29 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shiftfinishphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='service_app_photo_file_id',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='statement_photo_file_id',
        ),
    ]
