# Generated by Django 5.1.1 on 2024-11-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_remove_shift_confirmed_at'),
        ('staff', '0003_delete_staffavailabledate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('staff', 'date', 'is_extra')},
        ),
    ]
