# Generated by Django 5.1.1 on 2024-11-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_shift_is_active_shift_finished_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='shift',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
