# Generated by Django 5.1.1 on 2024-11-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_shift_is_confirmed_shift_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
