# Generated by Django 5.1.5 on 2025-02-02 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_alter_shift_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
