# Generated by Django 5.1.5 on 2025-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_alter_shift_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rejected at'),
        ),
    ]
