# Generated by Django 5.1.7 on 2025-03-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_shift_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartowash',
            name='windshield_washer_type',
            field=models.CharField(choices=[('water', 'Water'), ('antifreeze', 'Antifreeze')], default='antifreeze', max_length=16, verbose_name='Windshield washer type'),
        ),
    ]
