# Generated by Django 5.1.7 on 2025-04-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0014_shiftcarsthreshold_shift_transferred_cars_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindshieldWasherHidden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, help_text='Indicates if the windshield washer is hidden.', verbose_name='Is hidden')),
            ],
            options={
                'verbose_name': 'Windshield washer hidden',
                'verbose_name_plural': 'Windshield washer hidden',
            },
        ),
    ]
