# Generated by Django 5.1.7 on 2025-04-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_windshieldwasherhidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windshieldwasherhidden',
            options={'verbose_name': 'Windshield washer is hidden', 'verbose_name_plural': 'Windshield washer is hidden'},
        ),
    ]
