# Generated by Django 5.1.7 on 2025-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0016_alter_windshieldwasherhidden_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartowashadditionalservice',
            name='price_for_car_transporters_and_washers',
            field=models.PositiveIntegerField(default=0, help_text='price of additional service at the moment', verbose_name='Price for car transporters and washers'),
        ),
        migrations.AlterField(
            model_name='cartowashadditionalservice',
            name='price',
            field=models.PositiveIntegerField(help_text='price of additional service at the moment', verbose_name='Price for car transporters'),
        ),
    ]
