# Generated by Django 5.1.7 on 2025-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0017_cartowashadditionalservice_price_for_car_transporters_and_washers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartowash',
            name='item_dry_cleaning_price',
            field=models.PositiveIntegerField(default=50, help_text='price of item dry cleaning at the moment'),
        ),
    ]
