# Generated by Django 5.1.7 on 2025-06-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0018_cartowash_item_dry_cleaning_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftfinishphoto',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='photo URL'),
        ),
    ]
