# Generated by Django 5.1.1 on 2024-10-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('car_sharing_phone_number', models.CharField(max_length=16)),
                ('console_phone_number', models.CharField(max_length=16)),
            ],
        ),
    ]
