# Generated by Django 5.1.5 on 2025-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('transferred_car_number_help_text', 'Transferred car number help text'), ('transferred_car_class_help_text', 'Transferred car class help text')], max_length=255, unique=True)),
                ('value', models.TextField(max_length=1024)),
            ],
        ),
    ]
