# Generated by Django 5.1.7 on 2025-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dry_cleaning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryCleaningAdmin',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dry cleaning admin',
                'verbose_name_plural': 'Dry cleaning admins',
            },
        ),
    ]
