# Generated by Django 5.1.7 on 2025-04-09 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0003_staffregisterrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cars_count', models.PositiveSmallIntegerField(help_text='Minimum number of cars required to apply the bonus. Set to 0 to disable bonus.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum cars count')),
                ('bonus_amount', models.PositiveIntegerField(help_text='Amount of bonus to be applied. Set to 0 to disable bonus.', verbose_name='Bonus amount')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('excluded_staff', models.ManyToManyField(blank=True, to='staff.staff', verbose_name='Excluded from bonuses staff')),
            ],
            options={
                'verbose_name': 'Bonus settings',
                'verbose_name_plural': 'Bonus settings',
            },
        ),
    ]
